[phases.setup]
aptPkgs = [
  "libnspr4",
  "libnss3",
  "libatk-bridge2.0-0",
  "libgtk-3-0",
  "libgbm1",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libasound2",
  "libxshmfence1",
  "libdrm2",
  "libxfixes3",
  "libxkbcommon0",
  "libxcb1",
  "libxext6",
  "libxi6",
  "libxrender1",
  "libxss1",
  "libxtst6",
  "fonts-liberation",
  "ca-certificates"
]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
